Bsv20 - v2
BitcoinSchema/1sat-ordinals pull request #8
Opened 2023-08-21 17:51 UTC by shruggr

2023-08-21 18:11 UTC, jadwahab requested changes

2023-08-21 18:11 UTC, jadwahab commented on bsv20.md
> +  "p": "op-20",
typo "op-20"

2023-08-21 18:11 UTC, jadwahab commented on bsv20.md
> +  "op": "mint",
will there be no deploy operation for the tickerless deploy+mint?

2023-08-21 18:11 UTC, jadwahab commented on bsv20.md
> +| p | Yes | Protocol: `op-20` |
typo `op-20`

2023-08-21 18:11 UTC, jadwahab commented on bsv20.md
> +- {"p":"op-20","op":"transfer","id":"3b313338fa0555aebeaf91d8db1ffebd74773c67c8ad5181ff3d3f51e21e0000_1","amt":"100"}
typo

2023-08-21 18:11 UTC, jadwahab commented on bsv20.md
> +- {"p":"op-20","op":"transfer","id":"3b313338fa0555aebeaf91d8db1ffebd74773c67c8ad5181ff3d3f51e21e0000_1","amt":"500"}
typo

2023-08-21 18:11 UTC, jadwahab commented on bsv20.md
> +- {"p":"op-20","op":"transfer","id":"3b313338fa0555aebeaf91d8db1ffebd74773c67c8ad5181ff3d3f51e21e0000_1","amt":"400"}
typo -  just find and replace all

2023-08-30 16:12 UTC, rohenaz approved these changes
lgtm

2023-08-30 16:12 UTC, merged